site_name: mon-oral.net
theme:
  name: material
  custom_dir: overrides
  language: fr
  favicon: assets/images/mon-oral.svg
  logo: assets/images/mon-oral.svg
  palette:
    primary: white
    accent: green
  icon:
    repo: fontawesome/brands/git-alt

extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js 
extra:
  version:
    provider: mike
repo_url: https://github.com/mon-oral/documentation
edit_uri: ""
